import base64
import pickle
from typing import Any

import dill as dill_pickle


def serialize_tpot(model: Any) -> str:
    """
    Serializes the model using pickle and returns a base64 string.
    Kept for compatibility. May exceed 16MB in Mongo.
    """
    data = pickle.dumps(model, protocol=pickle.HIGHEST_PROTOCOL)
    return base64.b64encode(data).decode("ascii")


def load_model(model_pickle_b64: str) -> Any:
    """
    Reconstructs the model from the base64 string generated by serialize_tpot().
    Uses dill if available for greater compatibility.
    """
    if not isinstance(model_pickle_b64, str) or not model_pickle_b64.strip():
        raise ValueError("Invalid model_pickle_b64: provide the model's base64 string.")
    data = base64.b64decode(model_pickle_b64)
    return dill_pickle.loads(data)
